# Generated by Django 4.1.7 on 2023-03-31 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=200)),
                ('panels_id', models.CharField(max_length=200)),
                ('logitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Device',
            },
        ),
        migrations.CreateModel(
            name='Panels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panels_id', models.CharField(max_length=200)),
                ('wat', models.IntegerField()),
                ('max_volt', models.IntegerField()),
                ('panel_dim', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Panels',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=200)),
                ('bill_date', models.DateField()),
                ('ammount', models.IntegerField()),
                ('owner_name', models.CharField(max_length=200)),
                ('tt_divice', models.IntegerField()),
                ('tt_panels', models.IntegerField()),
                ('service_status', models.IntegerField()),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Device', to='digital_solar.device')),
                ('panels_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Panels', to='digital_solar.panels')),
            ],
            options={
                'verbose_name_plural': 'Customer',
            },
        ),
    ]
