# Generated by Django 4.1.7 on 2023-03-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_solar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='service_status',
            field=models.IntegerField(default=''),
        ),
    ]
