# Generated by Django 4.1.7 on 2023-03-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_solar', '0004_alter_voltages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voltages',
            name='bill_no',
            field=models.CharField(max_length=200),
        ),
    ]
